// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

const DB_USER = encodeURIComponent(process.env['DB_USER'] ?? 'build_user')
const DB_PASSWORD = encodeURIComponent(process.env['DB_PASSWORD'] ?? 'build_pass')
const DB_HOST = process.env['DB_HOST'] ?? 'localhost'
const DB_SCHEMA = process.env['DB_SCHEMA'] ?? 'db'
const DB_PORT = process.env['DB_PORT'] ?? '3306'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: `mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_SCHEMA}`,
  },
})
